server:
    tomcat:
        uri-encoding: UTF-8
        max-threads: 1000
        min-spare-threads: 30
    port: 80

spring:
    datasource:
        type: com.alibaba.druid.pool.DruidDataSource
        driverClassName: com.mysql.jdbc.Driver
        url: jdbc:mysql://182.61.60.110:3333/big-boot?useUnicode=true&characterEncoding=utf8&characterSetResults=utf8
        username: bigBoot
        password: ENC(qiGXbSKkn9Lzf3pTrui2tMK0qlG0+3+V)

#Zookeeper连接信息
zookeeper:
          url: 119.23.252.177
          port: 2181