server:
    tomcat:
        uri-encoding: UTF-8
        max-threads: 1000
        min-spare-threads: 30
    port: 9090
#Zookeeper连接信息
zookeeper:
          url: 119.23.252.177
          port: 2181
spring:
    datasource:
        type: com.alibaba.druid.pool.DruidDataSource
        driverClassName: com.mysql.jdbc.Driver
        url: jdbc:mysql://182.61.60.110:3333/big-boot?useUnicode=true&characterEncoding=utf8&characterSetResults=utf8
        username:
        password:
        redis:
                host: 182.61.60.110
                password: redis_123456
                port: 6379
                pool:
                  max-idle: 100
                  min-idle: 1
                  max-active: 1000
                  max-wait: -1
